F#src 4047 headless mode efficient
shadow-robot/sr_teleop_devices pull request #13
Opened 2020-03-05 16:12 UTC by carebare47

Checks / instructs arms in parallel when used with bimanual to half the wait times. Also now supports headless mode

2020-03-05 17:21 UTC, giusebar requested changes

2020-03-05 17:21 UTC, giusebar commented on sr_pedal/scripts/sr_ur_release.py
> +# Copyright 2019 Shadow Robot Company Ltd.
2020

2020-03-05 17:21 UTC, giusebar commented on sr_pedal/scripts/sr_ur_release.py
> +        if data.connected and data.left_pressed and data.right_pressed:
should we have that left button starts left and right starts right, in case we have unimanual? we can only process one arm instead of both

2020-03-05 17:21 UTC, giusebar commented on sr_pedal/scripts/sr_ur_release.py
> +        safety_mode_service = rospy.ServiceProxy("/" + arm + "_sr_ur_robot_hw/dashboard/get_safety_mode", GetSafetyMode)
could you add try-except, in case the service call fails.
e.g. 

try:
 serviceProxu
 return response
exept rospy.ServiceException, e:
   rospy.logerr("Service call failed")

2020-03-05 17:21 UTC, giusebar commented on sr_pedal/scripts/sr_ur_release.py
> +        get_mode_service = rospy.ServiceProxy("/" + arm + "_sr_ur_robot_hw/dashboard/get_robot_mode", GetRobotMode)
same as above

2020-03-05 17:21 UTC, giusebar commented on sr_pedal/scripts/sr_ur_release.py
> +                play_mode_service = rospy.ServiceProxy("/" + arm + "_sr_ur_robot_hw/dashboard/program_state", GetProgramState)
can't you use the call_dashboard_service function here as well?

2020-03-05 17:21 UTC, giusebar commented on sr_pedal/scripts/sr_ur_release.py
> +                play_mode_service = rospy.ServiceProxy("/" + arm + "_sr_ur_robot_hw/dashboard/program_state", GetProgramState)
use dashboard function?

2020-03-05 17:21 UTC, giusebar commented on sr_pedal/scripts/sr_ur_release.py
> +            self.check_arms_protective_stop(self.arms)
maybe in between checks, you can add a loginfo saying what we are checking?

2020-03-05 17:36 UTC, carebare47 commented on sr_pedal/scripts/sr_ur_release.py
> +# Copyright 2019 Shadow Robot Company Ltd.
Aha thanks 6d14b8b53b6602e7bbb3e5c08235031861c8d105

2020-03-05 17:38 UTC, carebare47 commented on sr_pedal/scripts/sr_ur_release.py
> +        if data.connected and data.left_pressed and data.right_pressed:
At the moment pressing both together starts/restarts whatever arm(s) are connected (left, right, or bimanual). I could change it so that left is for left and right is for right, but I think I'd have to do something clever to detect the left press while the right arm is checking/unlocking and then start the left check/unlock process before the right one finishes, unless we go back to waiting for left arm to finish checks/starts before doing the right arm. Could be a nicer way of doing it. Didn't think of that, do you think I should re-do it that way?

2020-03-05 17:46 UTC, carebare47 commented on sr_pedal/scripts/sr_ur_release.py
> +        safety_mode_service = rospy.ServiceProxy("/" + arm + "_sr_ur_robot_hw/dashboard/get_safety_mode", GetSafetyMode)
Like this? 58b3019ec5d20ad2ff0f383b57731f6f408e4800

2020-03-05 17:46 UTC, carebare47 commented on sr_pedal/scripts/sr_ur_release.py
> +        get_mode_service = rospy.ServiceProxy("/" + arm + "_sr_ur_robot_hw/dashboard/get_robot_mode", GetRobotMode)
58b3019ec5d20ad2ff0f383b57731f6f408e4800

2020-03-05 17:47 UTC, carebare47 commented on sr_pedal/scripts/sr_ur_release.py
> +                play_mode_service = rospy.ServiceProxy("/" + arm + "_sr_ur_robot_hw/dashboard/program_state", GetProgramState)
I could if I parameterised it to take different service types, at the moment the call_dashboard_service only calls services with the "Trigger" type

2020-03-05 17:52 UTC, carebare47 commented on sr_pedal/scripts/sr_ur_release.py
> +                play_mode_service = rospy.ServiceProxy("/" + arm + "_sr_ur_robot_hw/dashboard/program_state", GetProgramState)
How about this? 6d264b822ab2a6e522dbf08565edf92908a3c617

2020-03-05 17:52 UTC, carebare47 commented on sr_pedal/scripts/sr_ur_release.py
> +                play_mode_service = rospy.ServiceProxy("/" + arm + "_sr_ur_robot_hw/dashboard/program_state", GetProgramState)
6d264b822ab2a6e522dbf08565edf92908a3c617

2020-03-05 17:56 UTC, carebare47 commented on sr_pedal/scripts/sr_ur_release.py
> +            self.check_arms_protective_stop(self.arms)
df33d515539ab24f21a0f10ea2e48f0e67f4d82f

2020-03-18 13:04 UTC, mikramarc requested changes

2020-03-18 13:04 UTC, mikramarc commented on sr_pedal/launch/sr_pedal.launch
> +    <node name="sr_pedal_unlock" pkg="sr_pedal" type="sr_ur_release.py" output="screen"/>
this should not be running here. Thats what remapper is for.

2020-03-18 13:04 UTC, mikramarc commented on sr_pedal/scripts/sr_pedal_arm_remapper.py
> +        while not rospy.is_shutdown():
can we just rospy.spin at the end of the file instead of whole this?

2020-03-30 10:01 UTC, carebare47 commented on sr_pedal/scripts/sr_pedal_arm_remapper.py
> +        while not rospy.is_shutdown():
Yes :) 80f94e01a55542ae80d4b1e41a5504f81b380363

2020-03-30 10:03 UTC, carebare47 commented on sr_pedal/launch/sr_pedal.launch
> +    <node name="sr_pedal_unlock" pkg="sr_pedal" type="sr_ur_release.py" output="screen"/>
Done

2020-04-20 12:42 UTC, closed without merging