F#src 5598 fix pedal driver
shadow-robot/sr_teleop_devices pull request #29
Opened 2020-12-08 13:42 UTC by giusebar

Updated the pyusb pedal driver. This works with the newest pedals but does not work with older pedal.

2020-12-08 13:47 UTC, ToivoS approved these changes

2020-12-08 13:57 UTC, ethanfowler commented
Does the node survive the pedal USB connection going away and coming back?

2020-12-08 13:58 UTC, mikramarc requested changes, later dismissed

2020-12-08 13:58 UTC, mikramarc commented on sr_pedal/src/sr_pedal/sr_triple_pedal_pyusb.py
> +                except usb.core.USBError:
should we at least inform user that this is happenign?

2020-12-08 13:58 UTC, mikramarc commented on sr_pedal/src/sr_pedal/sr_triple_pedal_pyusb.py
> +        for cfg in device:
why loops if you are returning right away?
This seems equivalent to just
return device[0][0][0].bENdpointAddress

2020-12-08 13:58 UTC, mikramarc commented on sr_pedal/src/sr_pedal/sr_triple_pedal_pyusb.py
> +            self.endpoint_in = self.find_endpoint_in(self.device)
maybe find_endpoint_in_device?

2020-12-11 11:32 UTC, ToivoS approved these changes

2020-12-11 15:05 UTC, ethanfowler approved these changes

2020-12-11 17:31 UTC, ToivoS approved these changes

2020-12-11 17:36 UTC, merged