Add new driver for teleop pedal
shadow-robot/sr_teleop_devices pull request #33
Opened 2021-01-22 10:52 UTC by giusebar

## Proposed changes

New driver for the teleop pedal.

## Checklist

If the task is applicable to this pull request (see applicability criteria in brackets), make sure it is completed before checking the corresponding box. Otherwise, tick the box right away. Make sure that **ALL** boxes are checked **BEFORE** the PR is merged.

- [x] Manually tested that added code works as intended (if any functional/runnable code is added).
- [x] Added automated tests (if a new class is added (Python or C++), interface of that class must be unit tested).
- [x] Tested on real hardware (if the changed or added code is used with the real hardware).
- [x] Added documentation (For any new feature, explain what it does and how to use it. Write the documentation in a relevant space, e.g. Github, Confluence, etc.)

2021-01-22 11:03 UTC, biofotis requested changes
small year change. Should we remove the old triple pedal script as well ?

2021-01-22 11:03 UTC, biofotis commented on sr_pedal/src/sr_pedal/sr_pedal_driver.cpp
> +* Copyright (C) 2020 Shadow Robot Company Ltd - All Rights Reserved. Proprietary and Confidential.
2021?

2021-01-22 13:29 UTC, mykolasjuraitis commented on sr_pedal/include/sr_pedal/sr_pedal_driver.h
> +    char data_[8];
`data_` only seems to be used in method `read_data_from_device` so it could be local variable inside that method.

2021-01-22 13:31 UTC, mykolasjuraitis commented on sr_pedal/src/sr_pedal/sr_pedal_driver.cpp
> +  res = hid_read(device_handle, buffer_, sizeof(buffer_));
`res` is initialised to 0 and immediately rewritten with return value from `hid_read`. Maybe better just have:
```
int res = hid_read(device_handle, buffer_, sizeof(buffer_));
```

2021-01-22 13:41 UTC, mykolasjuraitis commented on sr_pedal/src/sr_pedal/sr_pedal_driver.cpp
> +    raw_data_received = data_[1];  // the second char of the buffer contains the button combination value
This bit is quite hard to comprehend. Isn't the second char already in `buffer_[0]`? Why to print it to `data_` instead of using directly?

2021-01-22 13:43 UTC, mykolasjuraitis commented on sr_pedal/include/sr_pedal/sr_pedal_driver.h
> +    sr_pedal::Status sr_pedal_status_;
`sr_pedal_status_` is only used in method `publish_pedal_data` so it could be local variable inside that method.

2021-01-22 13:48 UTC, mykolasjuraitis commented on sr_pedal/include/sr_pedal/sr_pedal_driver.h
> +    std::thread run_thread_;
This thread is never initialised just joined on stopping. Why it is needed?

2021-01-22 13:55 UTC, mykolasjuraitis commented on sr_pedal/include/sr_pedal/sr_pedal_driver.h
> +#define RAW_ALL_PRESSED_VALUE 55
Are these constants useful for external code? If they are just implementation details then they should be in cpp file not header file.

2021-01-22 14:01 UTC, mykolasjuraitis commented on sr_pedal/src/sr_pedal/sr_pedal_driver.cpp
> +      ros::Rate(publishing_rate_).sleep();
`publish_pedal_data` is called every control loop cycle but method `close_device` calls `publish_pedal_data` internally too, so if pedal is not detected then publishing will happen twice per control loop. Is such behaviour desired?

2021-01-22 14:04 UTC, mykolasjuraitis commented on sr_pedal/src/sr_pedal/sr_pedal_driver.cpp
> +    while (ros::ok())
Shouldn't condition be `while (ros::ok() && started_)`? Otherwise if `stop()` is called how this loop will be broken?

2021-01-22 14:22 UTC, giusebar commented on sr_pedal/src/sr_pedal/sr_pedal_driver.cpp
> +* Copyright (C) 2020 Shadow Robot Company Ltd - All Rights Reserved. Proprietary and Confidential.
addressed in https://github.com/shadow-robot/sr_teleop_devices/pull/33/commits/6d701b130c56c52e27bedbffca02ffe70be45e21

2021-01-22 14:22 UTC, giusebar commented on sr_pedal/include/sr_pedal/sr_pedal_driver.h
> +    char data_[8];
addressed in https://github.com/shadow-robot/sr_teleop_devices/pull/33/commits/6d701b130c56c52e27bedbffca02ffe70be45e21

2021-01-22 14:22 UTC, giusebar commented on sr_pedal/src/sr_pedal/sr_pedal_driver.cpp
> +  res = hid_read(device_handle, buffer_, sizeof(buffer_));
addressed in https://github.com/shadow-robot/sr_teleop_devices/pull/33/commits/6d701b130c56c52e27bedbffca02ffe70be45e21

2021-01-22 14:22 UTC, giusebar commented on sr_pedal/src/sr_pedal/sr_pedal_driver.cpp
> +    raw_data_received = data_[1];  // the second char of the buffer contains the button combination value
addressed in https://github.com/shadow-robot/sr_teleop_devices/pull/33/commits/6d701b130c56c52e27bedbffca02ffe70be45e21

2021-01-22 14:22 UTC, giusebar commented on sr_pedal/include/sr_pedal/sr_pedal_driver.h
> +    sr_pedal::Status sr_pedal_status_;
addressed in https://github.com/shadow-robot/sr_teleop_devices/pull/33/commits/6d701b130c56c52e27bedbffca02ffe70be45e21

2021-01-22 14:25 UTC, giusebar commented on sr_pedal/include/sr_pedal/sr_pedal_driver.h
> +    std::thread run_thread_;
addressed in https://github.com/shadow-robot/sr_teleop_devices/pull/33/commits/6d701b130c56c52e27bedbffca02ffe70be45e21

2021-01-22 14:25 UTC, giusebar commented on sr_pedal/include/sr_pedal/sr_pedal_driver.h
> +#define RAW_ALL_PRESSED_VALUE 55
addressed in https://github.com/shadow-robot/sr_teleop_devices/pull/33/commits/6d701b130c56c52e27bedbffca02ffe70be45e21

2021-01-22 14:25 UTC, giusebar commented on sr_pedal/src/sr_pedal/sr_pedal_driver.cpp
> +      ros::Rate(publishing_rate_).sleep();
addressed in https://github.com/shadow-robot/sr_teleop_devices/pull/33/commits/6d701b130c56c52e27bedbffca02ffe70be45e21

2021-01-22 14:25 UTC, giusebar commented on sr_pedal/src/sr_pedal/sr_pedal_driver.cpp
> +    while (ros::ok())
addressed in https://github.com/shadow-robot/sr_teleop_devices/pull/33/commits/6d701b130c56c52e27bedbffca02ffe70be45e21

2021-01-22 14:25 UTC, giusebar commented on sr_pedal/include/sr_pedal/sr_pedal_driver.h
> +    sr_pedal::Status sr_pedal_status_;
addressed in https://github.com/shadow-robot/sr_teleop_devices/pull/33/commits/5bcb4a9b98cea2bedbc359a544bce4a46b9c67a6

2021-01-22 14:32 UTC, mykolasjuraitis commented on sr_pedal/src/sr_pedal/sr_pedal_driver.cpp
> +    right_pressed_ = false;
It would probably be cleaner if these were moved to `map_command_received` and then `read_data_from_device` would have only single responsibility of reading.

2021-01-22 14:33 UTC, mykolasjuraitis commented on sr_pedal/include/sr_pedal/sr_pedal_driver.h
> +    unsigned char buffer_[8];
`buffer_` could be made local to method `read_data_from_device`.

2021-01-22 14:37 UTC, mykolasjuraitis commented on sr_pedal/src/sr_pedal/sr_pedal_driver.cpp
> +  int raw_data_received = 0;
This declaration could be merged with initialisation on line 131.

2021-01-22 14:42 UTC, mykolasjuraitis commented on sr_pedal/include/sr_pedal/sr_pedal_driver.h
> +    bool started_;
I am not used to this trailing underscore style. Is it mandatory for all private fields? If so, why `device_handle` doesn't have it?

2021-01-22 14:45 UTC, mykolasjuraitis commented on sr_pedal/CMakeLists.txt
> +  PATTERN ".svn" EXCLUDE
We are not using Subversion, should it be `.git` instead of `.svn`?

2021-01-22 14:54 UTC, mykolasjuraitis commented on sr_pedal/src/sr_pedal/sr_pedal_driver.cpp
> +}
This separate thread loop has exactly the same frequency and main control loop in `start` method. Is additional tread needed because `libusb_handle_events_completed` can block for long periods of time? From documentation it seems that it will block if not null pointer is passed but in null case it is not that clear.

2021-01-22 15:19 UTC, giusebar commented on sr_pedal/src/sr_pedal/sr_pedal_driver.cpp
> +}
It blocks without a separate thread also with nullptr. I added the the same frequency as main loop otherwise it will hang there and not join the thread on shutdown.

2021-01-22 15:20 UTC, giusebar commented on sr_pedal/CMakeLists.txt
> +  PATTERN ".svn" EXCLUDE
addressed in https://github.com/shadow-robot/sr_teleop_devices/pull/33/commits/5d168f376edd1583777f2b69655bb1766a5b6096

2021-01-22 15:21 UTC, giusebar commented on sr_pedal/include/sr_pedal/sr_pedal_driver.h
> +    bool started_;
missed it, ye we use the trailing underscore for private members in C++, not very necessary but most of our codebase has it. addressed in https://github.com/shadow-robot/sr_teleop_devices/pull/33/commits/5d168f376edd1583777f2b69655bb1766a5b6096

2021-01-22 15:21 UTC, giusebar commented on sr_pedal/src/sr_pedal/sr_pedal_driver.cpp
> +  int raw_data_received = 0;
addressed in https://github.com/shadow-robot/sr_teleop_devices/pull/33/commits/5d168f376edd1583777f2b69655bb1766a5b6096

2021-01-22 15:22 UTC, giusebar commented on sr_pedal/include/sr_pedal/sr_pedal_driver.h
> +    unsigned char buffer_[8];
if I make it local it will re-initialise the buffer everytime and lose a constant button press. not sure if there is a better way to do it.

2021-01-22 15:22 UTC, giusebar commented on sr_pedal/src/sr_pedal/sr_pedal_driver.cpp
> +    right_pressed_ = false;
addressed in https://github.com/shadow-robot/sr_teleop_devices/pull/33/commits/5d168f376edd1583777f2b69655bb1766a5b6096

2021-01-22 15:47 UTC, mykolasjuraitis approved these changes

2021-01-26 09:04 UTC, georgiablanco approved these changes

2021-01-26 09:53 UTC, biofotis approved these changes

2021-01-26 09:54 UTC, merged