Src 5562 hazard lights
shadow-robot/sr_teleop_devices pull request #40
Opened 2021-05-10 08:47 UTC by georgiablanco

## Proposed changes

Adding hazard light to teleop devices for [SRC-5562](https://shadowrobot.atlassian.net/browse/SRC-5562)

## Checklist

If the task is applicable to this pull request (see applicability criteria in brackets), make sure it is completed before checking the corresponding box. Otherwise, tick the box right away. Make sure that **ALL** boxes are checked **BEFORE** the PR is merged.

- [X] Manually tested that added code works as intended (if any functional/runnable code is added).
- [X] Added automated tests (if a new class is added (Python or C++), interface of that class must be unit tested).
- [X] Tested on real hardware (if the changed or added code is used with the real hardware).
- [X] Added documentation (For any new feature, explain what it does and how to use it. Write the documentation in a relevant space, e.g. Github, Confluence, etc.)

2021-05-10 11:54 UTC, mykolasjuraitis commented on sr_hazard_light/README.md
> +| Varaible | Details | Values |
Varaible -> Variable

2021-05-10 11:56 UTC, mykolasjuraitis commented on sr_hazard_light/include/sr_hazard_light/sr_hazard_light_driver.h
> +    std::vector<uint8_t> buffer = std::vector<uint8_t>(8);;
Double semicolon.

2021-05-10 12:04 UTC, mykolasjuraitis commented on sr_hazard_light/package.xml
> +  <url type="repository">https://github.com/shadow-robot/sr_teleop_internal</url>
Should it be `sr_teleop_devices`?

2021-05-10 12:06 UTC, mykolasjuraitis commented on sr_hazard_light/src/sr_hazard_light/sr_hazard_light_driver.cpp
> +    ret = libusb_hotplug_register_callback(context_,
You could have single statement:
```
int ret = libusb_hotplug_register_callback(context_,
```

2021-05-10 12:11 UTC, mykolasjuraitis commented on sr_hazard_light/src/sr_hazard_light/sr_hazard_light_driver.cpp
> +  std::uint8_t* buffer = &stop_buffer[0];
Why do you need vector here? Can't you just have:
```
uint8_t buffer[8] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
```

2021-05-10 12:13 UTC, mykolasjuraitis commented on sr_hazard_light/src/sr_hazard_light/sr_hazard_light_driver.cpp
> +    ROS_ERROR("Hazard light failed to set with error: %s\n", libusb_error_name(retval));
Doesn't `ROS_ERROR` terminate log entry by new line by default? Wouldn't having `\n` cause empty line?

2021-05-10 12:15 UTC, mykolasjuraitis commented on sr_hazard_light/src/sr_hazard_light/sr_hazard_light_driver.cpp
> +  exit(0);
Why do you need `exit` here?

2021-05-10 12:16 UTC, mykolasjuraitis commented on sr_hazard_light/src/sr_hazard_light/sr_hazard_light_driver.cpp
> +    ROS_ERROR("Hazard Light device not found\n");
Is `\n` necessary?

2021-05-10 12:16 UTC, mykolasjuraitis commented on sr_hazard_light/src/sr_hazard_light/sr_hazard_light_driver.cpp
> +    ROS_ERROR("libusb claim failed\n");
Is `\n` necessary?

2021-05-10 12:20 UTC, mykolasjuraitis commented on sr_hazard_light/src/sr_hazard_light/sr_hazard_light_driver.cpp
> +    patlite_handle = 0;
Almost exactly the same code is used in `stop` method. Maybe this block could be extracted to a separate method and used in both places.

2021-05-10 12:21 UTC, mykolasjuraitis commented on sr_hazard_light/src/sr_hazard_light/sr_hazard_light_driver.cpp
> +  ROS_INFO("Hazard light USB device opened and claimed\n");
Unnecessary new line `\n`.

2021-05-10 12:21 UTC, mikramarc requested changes

2021-05-10 12:21 UTC, mikramarc commented on sr_hazard_light/include/sr_hazard_light/sr_hazard_light_driver.h
> +        std::map<int16_t, hazard_light_data> red_light_timers;
I'd say i you are reusing same struct for four things and creating all those maps its better to create a generic class for light/buzzer with all the elements and methods like updates, than you dont need to repeat all the impolementations and its cleaner. So much duplicated code in those methjods

2021-05-10 12:21 UTC, mikramarc commented on sr_hazard_light/include/sr_hazard_light/sr_hazard_light_driver.h
> +        int default_key;
what does 'key' stand for. A bit unexplanatory.

2021-05-10 12:21 UTC, mikramarc commented on sr_hazard_light/include/sr_hazard_light/sr_hazard_light_driver.h
> +        std::map<int16_t, hazard_light_data> red_light_timers;
you could make a generic abstract class for both lights/buzzer and from it make child concrete classes for lights and for buzzer

2021-05-10 12:21 UTC, mikramarc commented on sr_hazard_light/include/sr_hazard_light/sr_hazard_light_driver.h
> +        int on_usb_hotplug(struct libusb_context *ctx,
maybe worth adding all the hotplub stuff to a separate class for modularization?

2021-05-10 12:23 UTC, mykolasjuraitis commented on sr_hazard_light/src/sr_hazard_light/sr_hazard_light_driver.cpp
> +  }
I think it would be more informative to split this check to 2 or 3 and not having "or" in the message so that user knows exactly what is wrong.

2021-05-10 12:25 UTC, mykolasjuraitis commented on sr_hazard_light/src/sr_hazard_light/sr_hazard_light_driver.cpp
> +    red_light_ = false;
You could write:
```
red_light_ = pattern != 0;
```

2021-05-10 12:27 UTC, mykolasjuraitis commented on sr_hazard_light/src/sr_hazard_light/sr_hazard_light_driver.cpp
> +bool::SrHazardLights::update_green_light(int pattern, int duration)
Methods `update_XXX_light` are too similar. There should be a way to abstract this code without so much repetition.

2021-05-10 12:28 UTC, mykolasjuraitis commented on sr_hazard_light/src/sr_hazard_light/sr_hazard_light_driver.cpp
> +    patlite_handle = 0;
Looks like you already have `send_buffer` method.

2021-05-10 14:38 UTC, mykolasjuraitis commented on sr_hazard_light/src/sr_hazard_light/sr_hazard_light_driver.cpp
> +    ros::Rate(publishing_rate_).sleep();
Both hoplug and other thread in start method have the same rate of sleeping. Do you need a separate thread for hotplug because `libusb_handle_events_completed` is blocking method? If it is blocking, then there is no point in sleeping here. If it is not blocking then there is no point in having 2 threads.

2021-05-10 14:42 UTC, mykolasjuraitis commented on sr_hazard_light/src/sr_hazard_light/sr_hazard_light_driver.cpp
> +    timer_map->erase(timer_key_remove);
You do the same think in both branches. If you really want to remove in both case then `erase` statement can be moved after `if/else`. Alternatively maybe you don't want to erase key in `else` as you didn't find it.

2021-05-10 14:43 UTC, mykolasjuraitis commented on sr_hazard_light/src/sr_hazard_light/sr_hazard_light_driver.cpp
> +    buzzer_on_ = false;
You can do:
```
buzzer_on_ = pattern != 0;
```
instead these 4 lines.

2021-05-10 15:01 UTC, georgiablanco commented on sr_hazard_light/src/sr_hazard_light/sr_hazard_light_driver.cpp
> +    ros::Rate(publishing_rate_).sleep();
It blocks without a separate thread also with nullptr. I added the the same frequency as main loop otherwise it will hang there and not join the thread on shutdown.

2021-05-10 15:02 UTC, mykolasjuraitis commented on sr_hazard_light/src/sr_hazard_light/sr_hazard_light_driver.cpp
> +    ros::Rate(publishing_rate_).sleep();
I see. Thanks for explanation.

2021-05-10 15:10 UTC, mykolasjuraitis commented on sr_hazard_light/CMakeLists.txt
> +  usb-1.0
I wonder if `${LIBUSB_1_LIBRARIES}` already includes `usb-1.0`?

2021-05-10 15:41 UTC, georgiablanco commented on sr_hazard_light/CMakeLists.txt
> +  usb-1.0
if i comment out `#include <libusb-1.0/libusb.h>` it fails

2021-05-11 10:19 UTC, biofotis approved these changes

2021-05-13 07:56 UTC, mykolasjuraitis approved these changes

2021-05-14 08:16 UTC, closed without merging