Src 5562 oop hazard light
shadow-robot/sr_teleop_devices pull request #43
Opened 2021-05-13 09:12 UTC by georgiablanco

## Proposed changes

Adding hazard light to teleop devices for [SRC-5562](https://shadowrobot.atlassian.net/browse/SRC-5562) with modularisation.
## Checklist

If the task is applicable to this pull request (see applicability criteria in brackets), make sure it is completed before checking the corresponding box. Otherwise, tick the box right away. Make sure that **ALL** boxes are checked **BEFORE** the PR is merged.

- [X] Manually tested that added code works as intended (if any functional/runnable code is added).
- [X] Added automated tests (if a new class is added (Python or C++), interface of that class must be unit tested).
- [X] Tested on real hardware (if the changed or added code is used with the real hardware).
- [X] Added documentation (For any new feature, explain what it does and how to use it. Write the documentation in a relevant space, e.g. Github, Confluence, etc.)

2021-05-13 09:33 UTC, mikramarc requested changes

2021-05-13 09:33 UTC, mikramarc commented on sr_hazard_light/include/sr_hazard_light/sr_hazard_light_driver.h
> +        virtual void change_topic_bool(std::vector<uint8_t> buffer) {};
please make pure virtual ( = 0;)

2021-05-13 09:33 UTC, mikramarc commented on sr_hazard_light/include/sr_hazard_light/sr_hazard_light_driver.h
> +        virtual bool set_light(int pattern,  int duration) {};
pure virtual

2021-05-13 09:33 UTC, mikramarc commented on sr_hazard_light/include/sr_hazard_light/sr_hazard_light_driver.h
> +                                    {0x00, 0x00, 0xFF, 0xFF, 0x0F, 0xFF, 0x00, 0x00});
these are characteristic to each color, I'd put them inside of class body instead of passing in constructor

2021-05-13 09:33 UTC, mikramarc commented on sr_hazard_light/src/sr_hazard_light/sr_hazard_light_driver.cpp
> +      if (!retval)
I'd suggest either using inline or using brackets, otherwise its easy to mess code up by adding another line, think its still in the if and mess up the code

2021-05-13 09:33 UTC, mikramarc commented on sr_hazard_light/src/sr_hazard_light/sr_hazard_light_driver.cpp
> +bool HazardLightRed::set_light(int pattern, int duration)
you could move this method to HazardLight and only change the line that is different (make it a virtual method and override it in base classes). That way you dont repeat code

2021-05-13 09:33 UTC, mikramarc commented on sr_hazard_light/src/sr_hazard_light/sr_hazard_light_driver.cpp
> +bool HazardLightRed::set_light(int pattern, int duration)
same as you do for change_topic_bool()

2021-05-13 09:33 UTC, mikramarc commented on sr_hazard_light/src/sr_hazard_light/sr_hazard_light_driver.cpp
> +SrHazardLights::SrHazardLights()
would be nice to have structore of code here (definitions of methods) in the same order as they are declated in header, makes it easier to read

2021-05-13 09:33 UTC, mikramarc commented on sr_hazard_light/src/sr_hazard_light/sr_hazard_light_driver.cpp
> +    retval = libusb_interrupt_transfer(patlite_handle, PATLITE_ENDPOINT_OUT, reset_buf, BUFFER_SIZE, &rs, 1000);
you could avoid all annoying retvals by just putting command inside an if

2021-05-13 09:33 UTC, mikramarc commented on sr_hazard_light/src/sr_hazard_light/sr_hazard_light_driver.cpp
> +  if (!patlite_handle)
make into one if?

2021-05-13 11:30 UTC, georgiablanco commented on sr_hazard_light/src/sr_hazard_light/sr_hazard_light_driver.cpp
> +    retval = libusb_interrupt_transfer(patlite_handle, PATLITE_ENDPOINT_OUT, reset_buf, BUFFER_SIZE, &rs, 1000);
but then it prints the retval [here](https://github.com/shadow-robot/sr_teleop_devices/blob/c188be2c34b708e953f0bb6b7a2fda05ba00820f/sr_hazard_light/src/sr_hazard_light/sr_hazard_light_driver.cpp#L70-L72)

2021-05-14 08:17 UTC, mykolasjuraitis approved these changes

2021-05-14 08:59 UTC, mikramarc requested changes

2021-05-14 08:59 UTC, mikramarc commented on sr_hazard_light/include/sr_hazard_light/sr_hazard_light_driver.h
> +        std::vector<uint8_t> buffer_default = std::vector<uint8_t>(8);
you can just do:
vector<uint_8> buffer_default(8);

2021-05-14 08:59 UTC, mikramarc commented on sr_hazard_light/include/sr_hazard_light/sr_hazard_light_driver.h
> +    public:
everything is public here, please keep only necessary bits public

2021-05-14 08:59 UTC, mikramarc commented on sr_hazard_light/include/sr_hazard_light/sr_hazard_light_driver.h
> +    public:
and in all methods below

2021-05-14 08:59 UTC, mikramarc commented on sr_hazard_light/include/sr_hazard_light/sr_hazard_light_driver.h
> +        ros::ServiceServer hazard_light_service;
does this need to be public?

2021-05-14 08:59 UTC, mikramarc commented on sr_hazard_light/include/sr_hazard_light/sr_hazard_light_driver.h
> +        bool is_on;
all member variables should have trailing underscore

2021-05-14 08:59 UTC, mikramarc commented on sr_hazard_light/include/sr_hazard_light/sr_hazard_light_driver.h
> +        std::vector<uint8_t> buffer_default = std::vector<uint8_t>(8);
also, do you even need to actually reserve memory if you're using copy constructor to fill it in right at the start in the initialization list?

2021-05-14 08:59 UTC, mikramarc commented on sr_hazard_light/src/sr_hazard_light/sr_hazard_light_driver.cpp
> +  if (duration == 0)
```suggestion
  if (0 == duration)
```

2021-05-14 08:59 UTC, mikramarc commented on sr_hazard_light/src/sr_hazard_light/sr_hazard_light_driver.cpp
> +  if (duration == 0)
```suggestion
  if (0 == duration)
```

2021-05-14 08:59 UTC, mikramarc commented on sr_hazard_light/src/sr_hazard_light/sr_hazard_light_driver.cpp
> +    is_on = false;
please make inline or with brackets

2021-05-14 08:59 UTC, mikramarc commented on sr_hazard_light/src/sr_hazard_light/sr_hazard_light_driver.cpp
> +  if ((buffer[2] & 0x0F) == 0x00)
```suggestion
  if (0x00 == (buffer[2] & 0x0F))
```

2021-05-14 08:59 UTC, mikramarc commented on sr_hazard_light/src/sr_hazard_light/sr_hazard_light_driver.cpp
> +    is_on = false;
please make inline or brackets

2021-05-14 08:59 UTC, mikramarc commented on sr_hazard_light/src/sr_hazard_light/sr_hazard_light_driver.cpp
> +    is_on = false;
same here

2021-05-14 08:59 UTC, mikramarc commented on sr_hazard_light/src/sr_hazard_light/sr_hazard_light_driver.cpp
> +    is_on = false;
and here

2021-05-14 08:59 UTC, mikramarc commented on sr_hazard_light/src/sr_hazard_light/sr_hazard_light_driver.cpp
> +    int ret = libusb_hotplug_register_callback(context_,
you're using retval in other places, maybe rename to be consistent?

2021-05-14 08:59 UTC, mikramarc commented on sr_hazard_light/src/sr_hazard_light/sr_hazard_light_driver.cpp
> +      started_ = true;
inline or brackets

2021-05-14 08:59 UTC, mikramarc commented on sr_hazard_light/src/sr_hazard_light/sr_hazard_light_driver.cpp
> +          open_device();
same

2021-05-14 08:59 UTC, mikramarc commented on sr_hazard_light/src/sr_hazard_light/sr_hazard_light_driver.cpp
> +        close_device();
same

2021-05-14 08:59 UTC, mikramarc commented on sr_hazard_light/src/sr_hazard_light/sr_hazard_light_driver.cpp
> +  bool retval = HazardEvent::send_buffer(stop_buffer);
not using retval

2021-05-14 08:59 UTC, mikramarc commented on sr_hazard_light/src/sr_hazard_light/sr_hazard_light_driver.cpp
> +    if (set_light_result && !complete_commands)
how does this even work? you dont change complete_commands so it will be true here so the content of the if will be false and again, you will not change that var

2021-05-14 08:59 UTC, mikramarc commented on sr_hazard_light/src/sr_hazard_light/sr_hazard_light_driver.cpp
> +  int ret = libusb_get_device_descriptor(device, &descriptor);
retval maybe for consistency?

2021-05-14 08:59 UTC, mikramarc commented on sr_hazard_light/src/sr_hazard_light/sr_hazard_light_driver.cpp
> +                                           {
indentation

2021-05-14 12:33 UTC, mikramarc approved these changes

2021-05-17 08:44 UTC, biofotis approved these changes

2021-05-17 08:46 UTC, biofotis approved these changes

2021-05-17 12:39 UTC, ethanfowler approved these changes

2021-05-17 12:43 UTC, merged