F#src 6560 fix leap noetic
shadow-robot/sr_teleop_devices pull request #45
Opened 2021-07-16 16:24 UTC by carebare47

## Proposed changes

Please explain the changes you made. Add pictures or videos to explain them better if appropriate.

## Checklist

If the task is applicable to this pull request (see applicability criteria in brackets), make sure it is completed before checking the corresponding box. Otherwise, tick the box right away. Make sure that **ALL** boxes are checked **BEFORE** the PR is merged.

- [ ] Manually tested that added code works as intended (if any functional/runnable code is added).
- [ ] Added automated tests (if a new class is added (Python or C++), interface of that class must be unit tested).
- [ ] Tested on real hardware (if the changed or added code is used with the real hardware).
- [ ] Added documentation (For any new feature, explain what it does and how to use it. Write the documentation in a relevant space, e.g. Github, Confluence, etc.)

2021-07-22 10:46 UTC, giusebar reviewed
I wonder whether we should try and make a PR against the ros-driver. For noetic? Might be nice for other people too

2021-07-22 10:46 UTC, giusebar commented on sr_leap_motion/scripts/install_leap.sh
> +cd /home/user && git clone https://github.com/BlackLight/leap-sdk-python3 && cd leap-sdk-python3 && sed -i 's/^SWIG=swig/SWIG=swig3.0/g' build.sh && make && sudo make install
we should probably get the user instead of doing home/user just in case we need to run it locally or user is not default

2021-07-22 10:46 UTC, giusebar commented on sr_leap_motion/src/sr_leap_ros_driver.py
> +        # print("Frame id: %d, timestamp: %d, hands: %d, fingers: %d, tools: %d, gestures: %d" % (
remove

2021-07-23 09:19 UTC, carebare47 commented
> I wonder whether we should try and make a PR against the ros-driver. For noetic? Might be nice for other people too

The old driver is c++ so I'm not sure that would be appropriate, but we could link them to this package in the issue?

2021-07-26 14:59 UTC, mikramarc requested changes

2021-07-26 14:59 UTC, mikramarc commented on sr_leap_motion/scripts/install_leap.sh
> +source /home/user/projects/shadow_robot/base_deps/devel/setup.bash && roscd leap_motion && rm -rf LeapSDK && sudo ln -s /home/user/leap-sdk-python3/leap/LeapSDK $(rospack find leap_motion)/LeapSDK
remove hardcoded paths. Also is the leap_motion folder correct? shouldnt it be sr_leap_motion?

2021-07-26 14:59 UTC, mikramarc commented on sr_leap_motion/src/sr_leap_ros_driver.py
> +    finger_names = ['Thumb', 'Index', 'Middle', 'Ring', 'Pinky']
are these values used anywhere? base class?

2021-07-26 14:59 UTC, mikramarc commented on sr_leap_motion/src/sr_leap_ros_driver.py
> +        print("Initialized")
use ros logging

2021-07-26 14:59 UTC, mikramarc commented on sr_leap_motion/src/sr_leap_ros_driver.py
> +        print("Connected")
use ros logging

2021-07-26 14:59 UTC, mikramarc commented on sr_leap_motion/src/sr_leap_ros_driver.py
> +        print("Connected")
and in other prints

2021-07-26 14:59 UTC, mikramarc commented on sr_leap_motion/src/sr_leap_ros_driver.py
> +        leap_matrix = basis
no need to just rename variable

2021-07-26 14:59 UTC, mikramarc commented on sr_leap_motion/src/sr_leap_ros_driver.py
> +    finger_names = ['Thumb', 'Index', 'Middle', 'Ring', 'Pinky']
shoudnt they also be member vars?

2021-07-26 14:59 UTC, mikramarc commented on sr_leap_motion/src/sr_leap_ros_driver.py
> +        for b in range(0, 4):
what is b, what is 4?

2021-07-26 14:59 UTC, mikramarc commented on sr_leap_motion/src/sr_leap_ros_driver.py
> +        for i in range(0, 3):
can we state why 3 in a variable here too?

2021-07-26 14:59 UTC, mikramarc commented on sr_leap_motion/src/sr_leap_ros_driver.py
> +    def on_disconnect(self, controller):
are those methods used anywhere?

2021-07-26 15:19 UTC, carebare47 commented on sr_leap_motion/scripts/install_leap.sh
> +cd /home/user && git clone https://github.com/BlackLight/leap-sdk-python3 && cd leap-sdk-python3 && sed -i 's/^SWIG=swig/SWIG=swig3.0/g' build.sh && make && sudo make install
https://github.com/shadow-robot/sr_teleop_devices/pull/45/files/ef0b2cce70d46fae0699b0372c0ace2203d0d733..c94dd1e5f8ae84e4d3c8637c8a54a3887850c2bd

2021-07-26 15:19 UTC, carebare47 commented on sr_leap_motion/scripts/install_leap.sh
> +source /home/user/projects/shadow_robot/base_deps/devel/setup.bash && roscd leap_motion && rm -rf LeapSDK && sudo ln -s /home/user/leap-sdk-python3/leap/LeapSDK $(rospack find leap_motion)/LeapSDK
how's this? https://github.com/shadow-robot/sr_teleop_devices/pull/45/files/ef0b2cce70d46fae0699b0372c0ace2203d0d733..c94dd1e5f8ae84e4d3c8637c8a54a3887850c2bd

leap_motion and sr_leap_motion are both packages

2021-07-27 08:40 UTC, carebare47 commented on sr_leap_motion/src/sr_leap_ros_driver.py
> +    def on_disconnect(self, controller):
they're overwriting methods in `Leap.Listener`

2021-07-27 10:26 UTC, carebare47 commented on sr_leap_motion/src/sr_leap_ros_driver.py
> +        # print("Frame id: %d, timestamp: %d, hands: %d, fingers: %d, tools: %d, gestures: %d" % (
It's quite useful for debug, I've changed it to this, what do you think? https://github.com/shadow-robot/sr_teleop_devices/blob/2f182a5df5680d63e7582bdf0715390eced817cb/sr_leap_motion/src/sr_leap_ros_driver.py#L175-L181

2021-07-27 13:18 UTC, mikramarc approved these changes

2021-07-27 13:53 UTC, georgiablanco approved these changes

2021-07-27 13:53 UTC, merged