Moved sr_piezo_feedback from common_resources to sr_teleop_devices
shadow-robot/sr_teleop_devices pull request #48
Opened 2022-02-08 10:40 UTC by maxzieba

## Proposed changes

Moving sr_piezo_feedback from common_resources

## Checklist

Before posting a PR ensure that from each of the below categories **AT LEAST ONE BOX HAS BEEN CHECKED**. If more than one category is applicable then more can be checked. Also ensure that the proposed changes have been filled out with relevant information for reviewers.

## Tests

- [X] No tests required to be added. (For small changes that will be tested by CI/CD infrastructure).
- [ ] Added/Modified automated and PhantomHand CI tests (if a new class is added (Python or C++), the interface of that class must be unit tested).
- [ ] Manually tested in simulation (if simulation specific or no hardware required to test the functionality). 
- [ ] Manually tested on hardware (if hardware specific or related).

## Documentation

- [X] No documentation required to be added.
- [ ] Added documentation (For any new feature, explain what it does and how to use it. Write the documentation in a relevant space, e.g. Github, Confluence, etc).
- [ ] Updated documentation (For changes to pre-existing features mentioned in the documentation).

2022-02-08 14:48 UTC, giusebar requested changes

2022-02-08 14:48 UTC, giusebar commented on sr_piezo_feedback/README.md
> +This class is used to transform tactile data received from the PST's sensors into output signal to provide haptic feedback.
PST or Biotacs. or maybe say hand E tactile sensors (currently PST or biotacs)

2022-02-08 14:48 UTC, giusebar commented on sr_piezo_feedback/README.md
> +For testing purposes only, **pst_source.py** was added which will mock the data provided through the **/rh/tactile** topic. The formulas/values there can be freely adjusted if required. To start the
since you added the biotac mock code, it would be good to mention it here too

2022-02-08 14:48 UTC, giusebar commented on sr_piezo_feedback/src/sr_piezo_feedback_node.py
> +    CONST_TOUCH_STRENGTH_DIFFERENCE = 0.02
can you add a comment explaining what these 2 const do?

2022-02-08 14:48 UTC, giusebar commented on sr_piezo_feedback/src/sr_piezo_feedback_node.py
> +        self._pdc_saturation = 100.0
i dont think we need to define this default values, because we are already defining them via the dynamic_recnofigure server defaults?

2022-02-08 14:48 UTC, giusebar commented on sr_piezo_feedback/src/sr_piezo_feedback_node.py
> +        self._amp_max = 1.0
i dont think we need to define this here since we already have default from dynamic reconfig

2022-02-08 15:48 UTC, maxzieba commented on sr_piezo_feedback/src/sr_piezo_feedback_node.py
> +        self._pdc_saturation = 100.0
The node starts before the default/changed values are initiatied by dynamic_reconfigure. Removing them here will crash the node. I can either assign some default values here or pass via rosparam at init time.

2022-02-08 17:27 UTC, giusebar approved these changes

2022-02-10 08:41 UTC, georgiablanco approved these changes

2022-02-10 08:43 UTC, merged